name: Prepare Workspace
description: Prepares the workspace for compilation

inputs:
  maven_username:
    required: false
    description: The username to use for the Maven server
  maven_password:
    required: false
    description: The password to use for the Maven server

runs:
  using: composite
  steps:
    - uses: Songoda-Plugins/GH-Commons/.github/actions/setup_workspace@main
      with:
        maven_username: ${{ inputs.maven_username }}
        maven_password: ${{ inputs.maven_password }}

    - uses: SpraxDev/Action-SpigotMC@v4
      with:
        versions: 1.20.1
